runtime: nodejs12
service: ds-servicea
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.50
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

env_variables:
  SERVICE_B_URL: "https://ds-serviceb-dot-dev1-onb-playground-18fd.appspot.com"
