apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dsns
  name:  myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: myweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myweb
    spec:
      containers:
      - image:  eu.gcr.io/deuba-gcr/public-images/nginx:1.16-alpine
        name:  myweb
        ports:
        - containerPort:  80
          name:  http