name: Main release

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build . --label "maintainer=Koenighotze" --label "version=${GITHUB_SHA}" --tag ${GITHUB_REPOSITORY}:${GITHUB_SHA}

      - name: Push image
        run: docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}  
      